Repository vaadin/vaadin-grid-pro, pull requests merged in 2019-01, with the labels that each got.

#19 feat(edit-column): add editModeRenderer support
  bower.json
  demo/index.html
  demo/pro-grid-edit-column-demos.html
  src/vaadin-pro-grid-edit-column.html
  src/vaadin-pro-grid-inline-editing-mixin.html
  test/edit-column.html
Labels: in progress

#21 Add boolean editor type support
  demo/pro-grid-edit-column-demos.html
  src/vaadin-pro-grid-edit-column-checkbox.html
  src/vaadin-pro-grid-edit-column.html
  test/edit-column.html
  theme/lumo/vaadin-pro-grid-edit-column-checkbox.html
  theme/lumo/vaadin-pro-grid-edit-column.html
  theme/material/vaadin-pro-grid-edit-column-checkbox.html
  theme/material/vaadin-pro-grid-edit-column.html
Labels: in progress

#22 refactor(edit-column): use focusous instead of blur
  demo/pro-grid-edit-column-demos.html
  src/vaadin-pro-grid-edit-column.html
  src/vaadin-pro-grid-inline-editing-mixin.html
  test/edit-column.html
Labels: in progress

#25 Polish cell editor appearance, add visual tests
  test/visual/default.html
  test/visual/edit-column-boolean.html
  test/visual/edit-column-select.html
  test/visual/edit-column-text.html
  test/visual/screens/vaadin-element/default-tests-lumo/vaadin-element/chrome.png
  test/visual/screens/vaadin-element/default-tests-lumo/vaadin-element/firefox.png
  test/visual/screens/vaadin-element/default-tests-material/vaadin-element/chrome.png
  test/visual/screens/vaadin-element/default-tests-material/vaadin-element/firefox.png
  test/visual/screens/vaadin-pro-grid/edit-column-boolean-tests-lumo/vaadin-pro-grid/chrome.png
  test/visual/screens/vaadin-pro-grid/edit-column-boolean-tests-lumo/vaadin-pro-grid/firefox.png
  test/visual/screens/vaadin-pro-grid/edit-column-boolean-tests-material/vaadin-pro-grid/chrome.png
  test/visual/screens/vaadin-pro-grid/edit-column-boolean-tests-material/vaadin-pro-grid/firefox.png
  test/visual/screens/vaadin-pro-grid/edit-column-select-tests-lumo/vaadin-pro-grid/chrome.png
  test/visual/screens/vaadin-pro-grid/edit-column-select-tests-lumo/vaadin-pro-grid/firefox.png
  test/visual/screens/vaadin-pro-grid/edit-column-select-tests-material/vaadin-pro-grid/chrome.png
  test/visual/screens/vaadin-pro-grid/edit-column-select-tests-material/vaadin-pro-grid/firefox.png
  test/visual/screens/vaadin-pro-grid/edit-column-text-tests-lumo/vaadin-pro-grid/chrome.png
  test/visual/screens/vaadin-pro-grid/edit-column-text-tests-lumo/vaadin-pro-grid/firefox.png
  test/visual/screens/vaadin-pro-grid/edit-column-text-tests-material/vaadin-pro-grid/chrome.png
  test/visual/screens/vaadin-pro-grid/edit-column-text-tests-material/vaadin-pro-grid/firefox.png
  test/visual/test.js
  theme/lumo/vaadin-pro-grid-edit-column-text-field.html
  theme/material/vaadin-pro-grid-edit-column-text-field.html
Labels: in progress

#30 fix(edit-column): ensure proper template and renderer observer calls
  src/vaadin-grid-pro-edit-column.html
  test/edit-column.html
Labels: in review

#31 fix(edit-column): cancel value change when exit edit mode on esc
  src/vaadin-grid-pro-inline-editing-mixin.html
  test/edit-column.html
Labels: in progress

#34 Use separate items array for each grid demo [skip ci]
  demo/grid-pro-basic-demos.html
  demo/grid-pro-common-modules-demos.html
  demo/grid-pro-demo.js
  demo/grid-pro-edit-column-demos.html
Labels: in progress

#33 chore(license): add vaadin-license-checker
  bower.json
  src/vaadin-grid-pro.html
Labels: in progress

#35 fix(edit-column): notify editor type change [skip ci]
  src/vaadin-grid-pro-edit-column.html
Labels: in progress

#37 Update text-field to latest alpha and fix flex regression
  theme/lumo/vaadin-grid-pro-edit-column-text-field.html
Labels: in progress

#52 breaking: rename column helper elements and boolean editor type
  demo/grid-pro-edit-column-demos.html
  src/vaadin-grid-pro-edit-checkbox.html
  src/vaadin-grid-pro-edit-column.html
  src/vaadin-grid-pro-edit-select.html
  src/vaadin-grid-pro-edit-text-field.html
  test/edit-column.html
  test/visual/edit-column-checkbox.html
  test/visual/screens/vaadin-grid-pro/edit-column-checkbox-tests-lumo/vaadin-grid-pro/chrome.png
  test/visual/screens/vaadin-grid-pro/edit-column-checkbox-tests-lumo/vaadin-grid-pro/firefox.png
  test/visual/screens/vaadin-grid-pro/edit-column-checkbox-tests-material/vaadin-grid-pro/chrome.png
  test/visual/screens/vaadin-grid-pro/edit-column-checkbox-tests-material/vaadin-grid-pro/firefox.png
  test/visual/test.js
  theme/lumo/vaadin-grid-pro-edit-checkbox.html
  theme/lumo/vaadin-grid-pro-edit-column-checkbox.html
  theme/lumo/vaadin-grid-pro-edit-column.html
  theme/lumo/vaadin-grid-pro-edit-select.html
  theme/lumo/vaadin-grid-pro-edit-text-field.html
  theme/material/vaadin-grid-pro-edit-checkbox.html
  theme/material/vaadin-grid-pro-edit-column-checkbox.html
  theme/material/vaadin-grid-pro-edit-column.html
  theme/material/vaadin-grid-pro-edit-select.html
  theme/material/vaadin-grid-pro-edit-text-field.html
Labels: in progress

#54 fix(edit-column): set focus-ring attribute on checkbox editor
  src/vaadin-grid-pro-edit-column.html
  test/edit-column.html
Labels: in progress

#55 fix: add missing imports check and warning
  src/vaadin-grid-pro-inline-editing-mixin.html
  test/.eslintrc.json
  test/basic.html
  test/helpers.html
Labels: in progress

#56 fix: workaround dblclick entering edit mode iOS Safari
  src/vaadin-grid-pro-inline-editing-mixin.html
  test/edit-column.html
Labels: in progress

#57 Refactor: rename confusing preserveEditMode and allowEnterRowChange
  demo/grid-pro-edit-column-demos.html
  src/vaadin-grid-pro-edit-select.html
  src/vaadin-grid-pro-inline-editing-mixin.html
  test/edit-column.html
Labels: dx/ux finding, in progress

#58 Check for string boolean value [skip ci]
  src/vaadin-grid-pro-edit-column.html
Labels: in progress
